- README.md
- src/index.js
- src/resizer.js
Allows someone to replace the handle style with any style they want. They can replace each style individually and it will use the default for the other handles.
Useful for making visible handles or changing the width of handles to tweak usability.
I started this because I want to have a box attached to the bottom of the screen and allow vertical resize with a handle at the top of the box. By the time I finished, I realized that I would also have to reverse how the amount is calculated, but this could be useful anyway so I will make a different PR to deal with my case and submit this one anyway.
> Add handleStyle property to resizer

- src/index.js
When I use Resizable and Draggable together, I need to do e.stopPropagation() in the resizeStart, it can make the Draggable to stop when I resizing the element.
> Pass e in the onResizeStart

- src/index.js
- test/test-resize-box.js
It enables a resizable box to keep a flexible dimension for width and height.
For example:
```JSX
<Resizable
width={100}
height="auto"
isResizable={ { right: true } }
/>
```
With this auto property, the box will preserve `height: auto` style after resizing its width.
> Support preserving auto size

- src/index.js
- src/resizer.js
- test/test-resizer.js
@bokuweb 
Related to https://github.com/bokuweb/react-rnd/issues/58
To change that `onTouchStart` method passing the whole event (as we discussed) I need to do adapt the `onResizeStart` method as well. And the test.
What do you think?
> Fixing issue on resizing with touch events

- src/index.js
There were some glitches when deltaWidth would go from > deltaH to < deltaH.
The check is not necessary and glitches should disappear now
> Always check Aspect ratio on both axis

- src/index.js
Fixes issue with resizable component being held in memory after component has been unmounted.
none
Component was completely removed after unmount happens.
> fix remove event listener

- index.d.ts
This pull request fixes a typescript error, where it's not possible to add DOM elements as children. For example
```js
<Resizable><div>Test</div></Resizable>
```
throws **Type 'Element[]' is not assignable to type 'ReactChildren | undefined'.**
`ResizableProps` in the typescript definition file has the `children` property as `ReactChildren` defined.
This should be `React.ReactNode` instead. We can remove it's definition completely as it is already defined in `React.Component`, which `Resizable` extends.
> Fixes typescript error with react children dom elements

- src/index.js
When user clicks with right button the resize is stuck in resizing mode
until users clicks again. We will prevent resize mode.
> Fix using right click on resize

- src/index.js
Related: https://github.com/WordPress/gutenberg/issues/3585
This pull request seeks to resolve errors which can occur in browsers not supporting ES6 or later (e.g. IE11). Specifically, `babel-preset-env` does not handle transpilation of prototype methods like `String#endsWith` or `Array#includes`. This is where [babel-polyfill](https://babeljs.io/docs/usage/polyfill/) would come in but, to avoid the heft of the polyfill, the proposed changes here merely replace the ES6 usage with an ES5 compatible alternative.
> Use ES5-compatible prototype methods

- README.md
- src/index.js
- stories/index.js
- stories/ratio/basic.js
- stories/ratio/fixed.js
- stories/ratio/header.js
- stories/ratio/sidebar.js
- test/index.test.js
Adds support for additional height and width when locking a resizable component to an aspect ratio. An example use case is a window that contains a 16:9 video and has a 50px header.
Fixes #163 
No significant tradeoffs. Width/height calculations are slightly more complex, but it should be negligible.
Added 6 additional tests. Also added stories to the storybook that illustrate the feature in action. Updated docs. Verified lint and tests pass.
> Fixes #163 - additional height and width with lockAspectRatio

- README.md
- src/index.js
- src/resizer.js
- stories/handle-component/bottom-right.js
- stories/index.js
- test/index.test.js
Add an option for passing custom handle components  as requested on #161 by @mrodigin. This allows for rendering of icons or any component that you'd like at any existing handle location.
React Components's passed in for each handle at `handleComponent[dir]` are rendered using `React.createElement` while `renderResizer` is iterating over each direction. This approach doesn't allow for props to be passed to the custom handle component at runtime. I first set the component to be rendered at `handleComponent[dir].component` and props at `handleComponent[dir].props` but it felt like overkill, i'd expect that this is mostly useful for rendering icons. This would be easy enough to change though if props were considered necessary. 
- Added a test to check if a custom component is rendered in …
> feat: Add a option for passing custom handle components

- index.d.ts
Currently using this package in TypeScript throws errors because of the following issues in type definitions in index.d.ts.
- Duplicate definitions
- ResizeDirection and ReactComponent is not defined errors 
- Making a couple of props as optional
This is a fix for the  issue  #191
> Fix type issues in index.d.ts 

- src/index.js
fix: #218 size not updated when zero props pass
> fix: #218 size not updated when zero props pass

- .eslintrc
- src/index.js
- stories/index.js
- stories/nested/nested.js
Related #220 
fix: bug,  error occurred when nesting
> fix: bug error occured when nested

- README.md
- package.json
- src/index.js
- stories/default-size/absolute-snap.js
- stories/index.js
- test/index.test.js
This PR is aiming to allow defining absolute snap dimensions, rather than an infinite grid. It also allows for selective axis definition, so you can absolutely snap only the `x` axis, for example.
e.g. 
`grid={[1,5]}` will land on `[1, 5]`, `[2, 5]`, as well as `[40, 50]` ad infinitum.
`snap={{ x: [20, 30, 50], y: [10] }}` will only land on `[20, 10]`, `[30, 10]`, `[50, 10]`.
Drawbacks: This solution puts priority of the absolute snap over the grid. Alternatively, it could snap to the defined grid after the absolute numbers, but I figured that'd be an odd developer experience since they're explicitly defining it to begin with.
There is an additional function added, `findClosestSnap` which does a reduce on the axis array. I've tried to keep this minimal and close to the `snap` function for …
> added feature: absolute snap dimensions

- src/index.js
Set the initial `element.style.left` property on the resizable container / `__resizable_base__` to 0 from the previous `-2147483647px`
In our specific use case (using this component, wrapped with a react-dnd component, on safari, our element was not draggable as the left position caused the draggable container to appear off-screen until manually adjusted to 0.
I can confirm that this works in the context of our application specifically-- tested in Chrome (latest) and Safari (latest). I have not been able to test this against other projects, nor do I know the original use case for the starting left value being `-2147483647px`.
Feel free to let me know if you have any questions or concerns, and to disregard this PR if it creates other issues!
> adjust intial left position of element to 0 for safari fix

- src/index.js
When putting `auto` as a size, it appends `px` after it, which is a problem, especially when going from a specific size (with `px`) and re-rendering back with `auto`, it kept the size.
Tested with my branch on the Embark UI repo: https://github.com/embark-framework/embark/tree/features/resizable-editor-main
> Fix auto having "px" appended

- README.md
- src/index.test.tsx
- src/index.tsx
- stories/snap.stories.tsx
Right now, the library allows snapping using `snap` or `grid` property but snapping is enforced. In this Pull Request, I'm adding a new `snapGap` prop that restricts the snapping behavior to a minimal gap between the computed size and the target snapping size.
This property works for both `snap` and `grid` snapping behavior. 
I added storybook stories to showcase the behavior.
> Add the possibility to limit snapping using a snapGap property

- src/index.test.tsx
- src/index.tsx
Add optional return boolean when calling onResizeStart to early exit and abort the resize sequence
(From ticket #494)
Currently, when `onResizeStart` is called, the user provided [`onResizeStart`](https://github.com/bokuweb/re-resizable/blob/master/src/index.tsx#L634) (from `props`) is also called. In certain scenarios, however, some condition may be hit where the user wants to abort the resize.
The feature request would be to allow the user to return a boolean from their defined `onResizeStart`, and if it returns `false`, the re-resizable's `onResizeStart` would have an early exit and not cause any resizing.
Should not add any overheard or tradeoffs. This `onResizeStart` is only stopped if the user returns an explicit `false`. I'm sure there are many cases where the return is undefined, …
> Fixes #494 Add optional abort for onResizeStart

- README.md
- src/index.tsx
> feat: adds support for vw, vh unit for maxHeight, maxWidth

- src/index.tsx
If we bind the mousemove event to `window`, it will always consume CPU while the mouse moving.
The solution is bind events after mousedown.
N/A
✅
> refactor: improve performance

- src/index.tsx
- stories/multiple.stories.tsx
Fixes issue #537
The width of the  resizable element was not the same of the expected one since the css property **flex-shrink** defaults to 1, with this, if the element size was greater than other subsequent element, the new updated width would diverge from the one assigned to the style prop, the simple solution would be passing this property as 0 blocking this kind of behavior
here is a gif showing what is the behavior after the fix:
> solving issue #537

- src/index.tsx
This PR makes the component window agnostic, which means that the component can be run inside an iframe.
We use this component in Gutenberg (WordPress) and we're experimenting rendering some of our components for site previewing inside an iframe. The resizable component errors because it assumes the top window.
Thank you for considering this PR!
Slightly more complex.
Yes
> Make component window agnostic

- src/index.tsx
`React.PureComponent` treats an absent state field differently from `undefined`, see [demo](https://codesandbox.io/s/hungry-bogdan-59zgi)
I added `flexBasis: undefined` to the initial state, to avoid re-renders after `componentDidUpdate` when possible
None
Tests pass
> Avoid a useless re-render

- README.md
- src/index.test.tsx
- src/index.tsx
- stories/wrapper.stories.tsx
In [Gutenberg](https://github.com/WordPress/gutenberg), we have this use-case where we want to control the DOM precisely (to match between the frontend and the editor), and for one of these components we're using Resizable as a wrapper but "div" is not always the right element we want to use there.
We have this particular use-case in a lot of places in our code base and in general we rely on a "as" prop to do so. Other react libraries also use this technique (example [Reakit](https://reakit.io/docs/basic-concepts/#as-prop)).
I don't know if you're interested by adding the same prop but In this PR I added support for it.
What do you think?
> Support the "as" prop to change the wrapper

- tsconfig.json
Fixes #634 
This solution, still builds the correct commonjs output because rollup will handle the module format conversion in that case.
No tradeoffs, this will give the expected build.
Tested locally.
> Fix ES Module Output Fixes #634

- src/index.tsx
window is a proxy in some micro-frontend scenes.
In such case, instanceof this.window.MouseEvent always return false.
Also, checking the exact property have better compatibility among different browsers
> fix: instanceof check fails when window is a proxy

- package.json
- yarn.lock
Using the Resizable component gets a compile error in typescript v4.0.3 when used with yarn 2 indicating the component is not setup correctly with props.
In addition, it's not possible to reference the component using the yarn 2 dependency mechanism because the react dependency is missing. This cannot be corrected by a yarn 2 "packageExtensions" because react and react-dom are incorrectly listed as devDependencies rather than peerDependencies.
None.
yarn test reported clean results. I also tried this (by publishing my own copy) with our code, and both the compile error and dependency problems were resolved.
> fix: Move react/react-dom to be peerDependencies instead of devDependencies

- README.md
- package.json
- src/index.tsx
bump version to 6.7.0
It PR about new feature.
Original behavior:
That behavior because window\`s right side close to resize component and component try resize like by right handler
`boundsByDirection` enabled behavior:
> Feature: boundsByDirection

- src/index.test.tsx
- src/index.tsx
Fixed #705 
The span has been changed to a div and as far as I can tell there is no side effect.
None
Working in Firefox, Chrome, Edge, IE11. Unit tests has been adapted
> Fixes #705

- src/index.tsx
Fixes #747
This is basically a revert of https://github.com/bokuweb/re-resizable/pull/152
Would be extremely happy if this can be merged and used by https://github.com/bokuweb/react-rnd  🙏
> Allow CTRL + click to be used for resizing

- src/index.tsx
Move snap before calculateNewSizeFromAspectRatio, that keeps new width and height follow lockAspectRatio
When set **lockAspectRatio** and **snap**, **snap** will break **lockAspectRatio**
None
Absolutely works
> fix: Should alway follow lockAspectRatio

- src/index.tsx
Fixes #764
None.
I have confirmed that this fix works.
> bugfix: calculate parent height even when the parent is a flex container

- README.md
- src/index.tsx
In current behavior, all resizers are disabled if we pass `false` to `ResizableProps.enable`.
https://github.com/bokuweb/re-resizable/blob/da458ab823949ee1090316a3d50950ff89a04a7d/src/index.tsx#L888-L890
However current type definition does not accept `false` so I fixed the type.
N/A
Tested with passing `false` to actual Resizable component.
> Add false to ResizableProps.enable

- README.md
- src/index.tsx
Introduces the ability to precisely control the resize ratio on both the x and y axies
No
Yes
> feat(resizeRatio): Support resizeRatioX and resizeRatioY

- src/index.tsx
Fixes `resizable` field always being `null` in React 18.3.
After [this React PR](https://github.com/facebook/react/pull/28348) for 18.3, `ref` is included as a normal prop. Because of this, we detect `ref` as a user-provided prop and break our ref logic. This causes the `resizable` field of our Resizable component to always read `null`. To fix this, we add `ref` to our defined props to ensure that we do not consider it a user-provided prop.
There should be no negative effects from this change.
For all users with React < 18.3, it is impossible to pass `ref` in `props` as it is removed by React, so this change will not affect them. For all users with React >= 18.3, this will fix the behavior of `ref` in their resizable component.
Tested accessing the `resizable` field in both React 18.0 and …
> Add `ref` to `definedProps`

- src/index.tsx
Callback refs defined as class functions don't get invoked in Next.js 14.2+ – and therefore don't work – perhaps because of changes to the underlying React which is at or near version 19.
This should fix https://github.com/bokuweb/react-rnd/issues/941 along with the related PR on react-rnd: https://github.com/bokuweb/react-rnd/pull/942
Tested and confirmed to work with the latest stable version of Next.js 14.2.3
> Define callback refs inline to work with latest versions of Next.js / React

- src/index.tsx
This fixes #820 that I just filed. Basically when using a boundary element that has transform scale the bounding box is not what you expect. 
Tested fix in my current project that uses this library, by modifying the index.js that is in the bundle with the same change.
> fix-boundary-scale: adds scaling to boundary Fixes #820
