bokuweb/re-resizable

package.json, src/index.js
In reference to issue https://github.com/bokuweb/react-sortable-pane/issues/25
=> default to full width / height

src/index.js
Stood out while browsing the code.
=> Fix Resizable spelling mistake

README.md, src/index.js
This adds support for a `grid` property, much like the one in `react-draggable`.
Please review 🙏
=> Add support for grid property

src/index.js
=> Window is not defined issue

index.d.ts
I have created a typescript declaration file to enable typescript for this library.
If you don't want to manage the typings in this repository I will push it to the definitelyTyped repo.
But it would be nice to have it here :)
=> added typescript definition file

src/resizer.js
=> Fixed angles' cursors

README.md
Found it in the code, but not mentioned in the docs
=> Include handle class documentation

package.json
=> chore(package): update eslint-plugin-flowtype to version 2.31.0

src/index.js
=> [#85] Fix recieve props

README.md, docs/dist/bundle.js, docs/index.html, docs/src/example.js, src/index.js, test/test-resize-box.js, yarn.lock
Wrap handler divs in a wrapper if a custom class / style is provided.
- Added a test case for handlerClass
- Using in production code
Based on #93 issue
=> Fixes #93 - Rendered resize handlers in wrapper (optional)

README.md, package.json, src/index.js
=> Remove should update component

package.json, src/index.js
=> fix style type

index.d.ts
replace accessor with class property
It fixes #153 
Used it with ts2.5, works without any error.
=> Update index.d.ts, Fixes #153

README.md, src/index.js, test/index.test.js
I have tried getting the tests to run, but eventually gave up - so I have NOT been able to run the tests on my machine (Windows env)...
=> Fixes #175 allow 0 as minWidth and minHeight

src/index.js
=> Fix auto sizing

src/index.js
fix: add guard to avoid error without parent
#155 
None
=> fix: add guard to avoid error without parent

src/index.js
=> fix: base id

src/index.js
fix: use relative when get size
=> Use relative for base

src/index.js
Fix Array method error in IE11
https://github.com/bokuweb/react-rnd/issues/299
=> fix: array method error in IE

index.d.ts
=> TypeScript: allow passing custom div props (fixes #292)

package.json, yarn.lock
=> fix: down rollup

src/index.js
=> fix: fix behavior whichi is set percent set and absolute position

src/index.js
=> fix: fix behavior when set auto

src/index.tsx
=> fix: use optional for gap and extrawidth and height

.storybook/preview-head.html, stories/aspect.stories.tsx, stories/basic.stories.tsx, stories/bounds.stories.tsx, stories/extra.stories.tsx, stories/handle.stories.tsx, stories/max.stories.tsx, stories/nested.stories.tsx, stories/ratio.stories.tsx, stories/scaled.stories.tsx, stories/size.stories.tsx, stories/snap.stories.tsx, tslint.json
=> add-stories

src/index.tsx, src/resizer.tsx, stories/flex.stories.tsx, tslint.json
=> Fix flex width

package.json, src/index.tsx
=> Use option for as

package.json, src/index.tsx
=> Fix touch event

src/index.tsx
NumberSize interface for ResizeCallback function param: delta
=> export NumberSize for ResizeCallback params

src/index.tsx
I changed to create base elemet if needed.
#667
=> fix: Fixed a base create timing to fix #667

package.json, src/index.tsx, src/resizer.tsx, yarn.lock
=> chore: reduce size

README.md
make it clear how to import the Resizable component.
=> docs(readme): add important statement

CHANGELOG.md, package.json, tsconfig.json
=> fix: 6.9.12

src/index.spec.tsx
=> fix: some specs

package.json, pnpm-lock.yaml, src/index.spec.tsx
=> Add some spec2

CHANGELOG.md, package.json
=> update minor version

src/index.spec.tsx, src/index.tsx
Reverts bokuweb/re-resizable#827
=> Revert "Match focus order to visual order"

.storybook/main.ts, package.json, pnpm-lock.yaml
=> deps: update react

package.json
=> fix: v6.0.3

src/index.spec.tsx
=> fix: mask it

src/resizer.tsx
**difficult to resize using `Rnd` Corners specially bottom-right corner/edge**
https://github.com/user-attachments/assets/791c6a3a-9f40-4d56-b8a3-5000ece5c6dc
=> Rnd Corner Resizers z-index

package.json
=> env: update to 6.11.0

src/index.spec.tsx
=> spec: revive some tests

package.json, src/index.tsx, src/resizer.tsx, tsconfig.json, tsconfig.test.json
=> refactor: use functional comp for resizer
